window.portfolioWorks = [
  {
    title: "Power Core",
    category: "3D Artwork",
    description:
      "An in-development industrial prop with a tactical silhouette and strong panel logic. This piece explores how a power system could actually fit into a believable game environment.",
    tools: ["Blender", "In Development", "Hard Surface"],
    glbPath: "models/POWER CORE6.glb",
    renderPath: "render/POWER_CORE_RENDER.png",
    wireframePath: "wireframe/POWER_CORE_WIREFRAME.png",
    availableViews: ["render", "solid", "wireframe"],
    allowModelDownload: false,
    purchaseUrl: "https://gumroad.com/",
    actionText: "Coming soon on Gumroad",
    commerceBadge: "Gumroad soon",
    glbLabel: "In development",
    artClass: "project-art-one",
  },
  {
    title: "Crate Final",
    category: "Completed Work",
    description:
      "A finished stylized crate asset designed for a larger environment. The focus here was clean shape language, strong presentation, and a game-ready industrial look.",
    tools: ["Finished Piece", "Game Prop", "Presentation"],
    glbPath: "models/CRATE_FINAL.glb",
    renderPath: "render/CRATE_FINAL_RENDER.png",
    wireframePath: "wireframe/CRATE_FINAL_WIREFRAME.png",
    availableViews: ["render", "solid", "wireframe"],
    allowModelDownload: true,
    actionText: "Open 3D model",
    commerceBadge: "",
    glbLabel: "Completed",
    artClass: "project-art-two",
  },
  {
    title: "Wall Solo",
    category: "Environment Component",
    description:
      "A structural wall piece from the main crate environment. It is built to support modular worldbuilding, giving the environment a believable industrial backbone.",
    tools: ["Modular Design", "Environment", "Structure"],
    glbPath: "models/WALL_SOLO.glb",
    renderPath: "render/wall-solo.jpg",
    wireframePath: "wireframe/wall-solo.png",
    availableViews: ["solid"],
    allowModelDownload: true,
    actionText: "Open 3D model",
    commerceBadge: "",
    glbLabel: "Environment part",
    artClass: "project-art-three",
  },
  {
    title: "Rusty Metal Material",
    category: "Material Study",
    description:
      "A surface and material lookdev study focused on rusty metal response, contrast, and presentation. This helps refine how materials read under clean studio lighting.",
    tools: ["Material Study", "Lookdev", "Surface Work"],
    glbPath: "models/RUSTY_METAL_SPHERE.glb",
    renderPath: "render/rusty-metal-material.jpg",
    wireframePath: "wireframe/rusty-metal-material.png",
    availableViews: ["solid"],
    allowModelDownload: true,
    actionText: "Open 3D model",
    commerceBadge: "",
    glbLabel: "Material test",
    artClass: "project-art-four",
  },
];
